### PR TITLE
fix: use synckit to support Prettier 3

### LINKED ISSUE #171: Prettier 3.0
Prettier just [released a new major version](https://prettier.io/blog/2023/07/05/3.0.0.html) which includes some breaking changes to the API. Currently Prettier 3.0 causes the extension to throw a type error:

```
Error: Expected `input` to be a `string`, got `object` 
TypeError: Expected `input` to be a `string`, got `object`
```

I haven't looked into the source code for Prettier or this extension for a while so I don't know how difficult of a fix this is.

If anyone is having this same issue, the short term solution is to explicitly install a version of prettier before 3.0.
```bash
npm i -D prettier@2.8.8
```

### PR DESCRIPTION
**Pull request by idahogurl**
## What
Closes #171 

### Breaking Changes
- `prettier-eslint` must be installed locally by the user
- Prettier v3.0 is now required
- ESLint >= v8.52.0 is now required

## Why
Prettier 3 added a dynamic `import()` in its .cjs file, making ESM support required. VS Code only supports CommonJS (CJS) however. According to this comment https://github.com/prettier/prettier-vscode/pull/2947#issuecomment-1575066828, VSCode extensions can use `worker_threads` and a Worker can execute `import()`.

Thus, this PR makes it so that instances of `prettier-eslint` are run on Worker of `worker_threads.`

### CODE REVIEW

**Comment by JounQin** [comment]
That doesn't matter with external and no need to bundle at all for regular commonjs, but I'm not so familiar with VSCode/vmscripts.

Regularly, `await import('esm.mjs')` is just supported, so `await import('prettier')` should just work.

If it doesn't work, then `synckit` should be a good choice.

File: src/extension.js [hunk 1]
```diff
@@ -6,51 +6,71 @@
...
+      return [];
     }
+
+    const startLine = document.lineAt(0);
+    const endLine = document.lineAt(document.lineCount - 1);
+    const range = new Range(startLine.range.start, endLine.range.end);
+    const text = document.getText(range);
+    const prettierLast = workspace.getConfiguration('vs-code-prettier-eslint').get('prettierLast');
+
+    const formatText = createSyncFn(require.resolve('./worker'));
```
Comment (idahogurl) [inline src/extension.js:60]: @JounQin Should I calculate the byte size of the document text for the bufferSize?

Comment (JounQin) [reply src/extension.js:60]: You don't need to.

File: src/worker.js [hunk 2]
```diff
@@ -0,0 +1,14 @@
+import { runAsWorker } from 'synckit';
+
+runAsWorker(async ({
+  text, prettierEslintPath, filePath, extensionConfig,
+}) => {
+  // eslint-disable-next-line import/no-dynamic-require, global-require
+  const format = require(prettierEslintPath);
```
Comment (JounQin) [inline src/worker.js:7]: 1. I don't think you need to use `require` here
2. My first thought is: we don't need any worker, just use `await import('prettier')` in the main thread if sync is not required

File: src/worker.js [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+  return format({
+    text,
+    filePath,
+    logLevel: 'info',
+    prettierLast: extensionConfig?.prettierLast || false,
```
Comment (JounQin) [inline src/worker.js:12]:
```suggestion
    prettierLast: extensionConfig?.prettierLast,
```

Personally, I think we should not add such useless default value.

File: package.json [hunk 4]
```diff
@@ -48,10 +48,11 @@
...
     "test": "node ./test/runTest.js",
     "test:update": "SNAPSHOT_UPDATE=true node ./test/runTest.js",
-    "dev": "NODE_ENV=dev node ./scripts/build.js",
-    "watch": "NODE_ENV=dev,watch node ./scripts/build.js",
-    "build": "NODE_ENV=prod node ./scripts/build.js",
-    "package": "yarn build && vsce package --yarn",
+    "dev": "esbuild ./src/extension.js --bundle --platform=node --target=node16 --external:vscode --external:@typescript-eslint/parser --external:vue-eslint-parser --outfile=./dist/extension.js",
+    "dev:watch": "yarn dev --watch --sourcemap",
+    "build": "yarn dev --minify",
+    "build:worker": "esbuild ./src/worker.js --bundle --platform=node --target=node16 --outfile=./dist/worker.js",
```
Comment (JounQin) [inline package.json:54]: You don't need to compile the worker.

File: package.json [hunk 5]
```diff
@@ -48,10 +48,11 @@
     "pretest": "yarn lint",
     "test": "node ./test/runTest.js",
     "test:update": "SNAPSHOT_UPDATE=true node ./test/runTest.js",
-    "dev": "NODE_ENV=dev node ./scripts/build.js",
-    "watch": "NODE_ENV=dev,watch node ./scripts/build.js",
-    "build": "NODE_ENV=prod node ./scripts/build.js",
-    "package": "yarn build && vsce package --yarn",
+    "dev": "esbuild ./src/extension.js --bundle --platform=node --target=node16 --external:vscode --external:@typescript-eslint/parser --external:vue-eslint-parser --outfile=./dist/extension.js",
```
Comment (JounQin) [inline package.json:51]: My two cents, `await import()` is compiled into `require` incorrectly, you should use the hack instead of using `require`

**Comment by JounQin** [comment]
If you need any help, I can help to raise a new PR based on this one later for you.

File: package.json (hunk 4 above)
Comment (idahogurl) [reply package.json:54]: @JounQin I have to bundle synckit that is why I'm compiling it.

Comment (JounQin) [reply package.json:54]: You don't need to.

Comment (idahogurl) [reply package.json:54]: @JounQin Why don't I need to bundle it?

Comment (JounQin) [reply package.json:54]: Can't we mark it as dependency?

Comment (idahogurl) [reply package.json:54]: @JounQin I could but I'm trying to keep the amount of dependencies the user has to install to a minimum.

Comment (JounQin) [reply package.json:54]: OK, that may be valid thought, but it complexes the whole workflow, I don't think that worth too much.

File: src/extension.js (hunk 1 above)
Comment (JounQin) [inline src/extension.js:60]: https://github.com/idahogurl/vs-code-prettier-eslint/issues/171#issuecomment-1848082004

Move it outside to preload worker before first run.

File: src/worker.js (hunk 2 above)
Comment (idahogurl) [reply src/worker.js:7]: @JounQin Dynamic imports are not supported by VS Code. I get the error `A dynamic import callback was not specified` when I try to use a dynamic import even with the hack. As you will see in this comment https://github.com/prettier/prettier-vscode/issues/3007#issuecomment-1596203079, it was fixed by using worker threads.

Comment (JounQin) [reply src/worker.js:7]: OK, sorry I'm lacking of VSCode skills.

File: CHANGELOG.md [hunk 6]
```diff
@@ -1,3 +1,14 @@
+# v6.0.0 (Fri Dec 1 2023)
+
+#### 🚀 Enhancement
+
+- fix: use worker_threads to support Prettier 3
```
Comment (JounQin) [inline CHANGELOG.md:5]:
```suggestion
- fix: use `worker_threads` via [`synckit`](https://github.com/un-ts/synckit) to support Prettier 3
```

Can you mention `synckit` in changelog?

File: src/worker.js (hunk 2 above)
Comment (JounQin) [reply src/worker.js:7]: But it's already inside a worker now, so `import()` should be supported here?

File: package.json [hunk 7]
```diff
@@ -66,23 +67,26 @@
...
     "ts-node": "^10.9.1",
     "typescript": "^4.9.5",
     "vsce": "^2.15.0"
   },
   "dependencies": {
     "find-up": "^6.3.0",
     "ignore": "^5.2.4",
-    "prettier-eslint": "^15.0.1"
+    "require-relative": "^0.8.7",
+    "synckit": "^0.8.6"
```
Comment (JounQin) [inline package.json:89]: It's marked as dependency here, do we really need to bundle it? Again, I'm lacking knowledge of VSCode, feel free to tell that I'm wrong here.

File: package.json [hunk 8]
```diff
@@ -66,23 +67,26 @@
     "all-contributors-cli": "^6.24.0",
     "auto": "^10.42.2",
     "esbuild": "^0.16.14",
+    "esbuild-plugin-copy": "^2.1.1",
     "esbuild-plugin-text-replace": "^1.2.0",
-    "eslint": "^8.31.0",
+    "eslint": "8.52.0",
```
Comment (JounQin) [inline package.json:72]:
```suggestion
    "eslint": "^8.52.0",
```

I don't see any reason to lock the version?

File: src/worker.js (hunk 2 above)
Comment (JounQin) [inline src/worker.js:7]:
```suggestion
  const format = import(prettierEslintPath);
```

File: src/extension.js [hunk 9]
```diff
@@ -71,8 +91,14 @@ const supportedLanguages = [
...
+    provideDocumentRangeFormattingEdits(document) {
+      return formatter(document);
+    },
+  });
 });
 
 // Create output channel for error logging
 outputChannel = window.createOutputChannel('Prettier Eslint');
+
+formatText = createSyncFn(require.resolve('./worker'));
```
Comment (JounQin) [inline src/extension.js:104]: I don't get why it's not just be created inline?

File: src/extension.js [hunk 10]
```diff
@@ -6,51 +6,71 @@
...
+import requireRelative from 'require-relative';
 
-import format from './formatter';
-import { isFilePathMatchedByEslintIgnore, isFilePathMatchedByPrettierIgnore } from './ignore';
-
-const path = require('path');
+import isFilePathMatchedByIgnore from './ignore';
 
 let outputChannel;
+let formatText;
```
Comment (JounQin) [inline src/extension.js:16]:
```suggestion
const formatText = createSyncFn(require.resolve('./worker'));
```

File: src/worker.js (hunk 2 above)
Comment (idahogurl) [reply src/worker.js:7]: It's got me confused too because I tried it and it caused the extension to hang.

File: src/extension.js [hunk 11]
```diff
@@ -6,51 +6,71 @@
...
+import { createSyncFn } from 'synckit';
+import requireRelative from 'require-relative';
 
-import format from './formatter';
-import { isFilePathMatchedByEslintIgnore, isFilePathMatchedByPrettierIgnore } from './ignore';
-
-const path = require('path');
+import isFilePathMatchedByIgnore from './ignore';
 
 let outputChannel;
```
Comment (JounQin) [inline src/extension.js:15]:
```suggestion
const outputChannel = window.createOutputChannel('Prettier Eslint');
```

**Comment by JounQin** [comment]
Can you update the PR title accordingly?

File: src/worker.js (hunk 2 above)
Comment (JounQin) [reply src/worker.js:7]: Do you mean with `synckit` or without? You can use the `SYNCKIT_TIMEOUT` environment or `timeout` option to debug.

File: package.json [hunk 12]
```diff
@@ -66,23 +67,26 @@
     "all-contributors-cli": "^6.24.0",
     "auto": "^10.42.2",
     "esbuild": "^0.16.14",
+    "esbuild-plugin-copy": "^2.1.1",
```
Comment (JounQin) [inline package.json:70]:
```suggestion
```

I didn't see any usage of this package.

File: src/worker.js (hunk 2 above)
Comment (idahogurl) [reply src/worker.js:7]: @JounQin I tried the timeout option and I get `Error: Internal error: Atomics.wait() failed: timed-out`
I'm trying this:
```javascript
const format = await import(prettierEslintPath);
  return format.default({
    text,
    filePath,
    prettierLast: extensionConfig?.prettierLast,
  });
```

File: package.json (hunk 7 above)
Comment (idahogurl) [reply package.json:87]: @JounQin I tried without bundling it and it causes the extension to hang.

File: src/worker.js (hunk 2 above)
Comment (JounQin) [reply src/worker.js:7]: I'll help to debug today later.

Comment (JounQin) [reply src/worker.js:7]: `prettierPath` could be ESM, so I think we should fix it before releasing.

File: package.json (hunk 7 above)
Comment (JounQin) [reply package.json:87]: Let me see if I can help.

File: src/worker.js (hunk 2 above)
Comment (JounQin) [reply src/worker.js:7]: I tiny guess is that you're using esbuild to bundle this file as commonjs, this is not supported, so you should use `worker.mjs` instead.

Comment (idahogurl) [reply src/worker.js:7]: Not bundling it. I tried 'worker.mjs' and just copying the file directly to the 'dist' folder.

Comment (JounQin) [reply src/worker.js:7]: image

I didn't see any `vscode-prettier-eslint` related output after changing codes and re-packaging + installing from `.vsix`.

Comment (JounQin) [reply src/worker.js:7]: image

I'm not a VSCode expert, any idea?

Comment (JounQin) [reply src/worker.js:7]: See #201 @idahogurl

File: package.json (hunk 4 above)
Comment (JounQin) [reply package.json:54]: Bundling is required by vscode even for `dependencies`, see https://github.com/microsoft/vscode/issues/200433 for tracking.

**Comment by netux** [comment]
I did some quick debugging and found out there is still a bottleneck with the worker having to load `prettier-eslint`, which on my machine takes roughly 2-3 seconds.

Also the preload did nothing for me because, from a VSCode window reload with a document already opened, the extension is only activated when the formatter is run.

I think a solution would be to:
1. Add `onStartupFinished` to the `"activationEvents"` field in the package.json, to make sure the extension is ready after VSCode starts.
2. On load, run `formatText()` with some dummy document to force the engine to go through the code paths that a real document would go through, and load all the necessary things that way.

**Comment by JounQin** [comment]
@netux I think you can just raise a PR for your proposal.

**Comment by netux** [comment]
> @netux I think you can just raise a PR for your proposal.

Good idea! I have opened #202 🙂.

File: package.json [hunk 13]
```diff
@@ -48,10 +48,13 @@
     "pretest": "yarn lint",
     "test": "node ./test/runTest.js",
     "test:update": "SNAPSHOT_UPDATE=true node ./test/runTest.js",
-    "dev": "NODE_ENV=dev node ./scripts/build.js",
-    "watch": "NODE_ENV=dev,watch node ./scripts/build.js",
-    "build": "NODE_ENV=prod node ./scripts/build.js",
-    "package": "yarn build && vsce package --yarn",
+    "dev:watch": "yarn dev --watch --sourcemap",
+    "build:dev": "yarn build:extension && yarn build:worker",
+    "build": "yarn build:extension --minify && yarn build:worker --minify",
```
Comment (JounQin) [inline package.json:53]: Should we enable `--sourcemap` for better debugging experience? @idahogurl

**Review by JounQin — APPROVED** [review]

File: package.json (hunk 13 above)
Comment (idahogurl) [reply package.json:55]: @JounQin Depends if the sourcemap will be used when an error is thrown. I think we are fine without it.

Comment (JounQin) [reply package.json:55]: Sourcemap will be used when error thrown, it was a bit painful to debug what caused `import()` not working. If there are sourcemaps, when people report issues, we'll find the root cause much easier.

Comment (idahogurl) [reply package.json:55]: @JounQin Let's add sourcemaps then.

Comment (JounQin) [reply package.json:55]: @idahogurl Do you want a new PR or you'll just add that?

Comment (idahogurl) [reply package.json:55]: @JounQin I'll add it.

File: src/extension.js [hunk 14]
```diff
@@ -70,9 +90,61 @@ const supportedLanguages = [
...
+/**
+ * Provides a promise that resolves as soon as there is an active text editor
+ * with a document open on a language this extension supports.
+ *
+ * @returns {Promise<TextDocument>}
+ */
+function waitForActiveSupportedDocument() {
+  if (
+    !window.activeTextEditor
+    || !supportedLanguages.includes(window.activeTextEditor.document.languageId)
```
Comment (JounQin) [inline src/extension.js:102]: I believe `supportedLanguages` should not be hard coded because of 3rd-party plugins. But it can be done in next minor version, I'd like to PR after v3 released later.

**Review by JounQin — APPROVED** [review]

**Comment by JounQin** [comment]
I think we are just ready to go! Congratulations!

File: package.json [hunk 15]
```diff
@@ -66,23 +72,24 @@
...
     "ts-node": "^10.9.1",
     "typescript": "^4.9.5",
     "vsce": "^2.15.0"
   },
   "dependencies": {
     "find-up": "^6.3.0",
     "ignore": "^5.2.4",
-    "prettier-eslint": "^15.0.1"
+    "require-relative": "^0.8.7",
+    "synckit": "^0.8.6"
```
Comment (JounQin) [inline package.json:92]:
```suggestion
    "synckit": "^0.9.0"
```

It's much smaller now.

Comment (JounQin) [reply package.json:92]: See #207 @idahogurl
